name: ci-test

on:
  push:
    branches:
      - master

jobs:
  test:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: testserver
          POSTGRES_PASSWORD: passw0rd
          POSTGRES_DB: testserverdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pgmigrate
        run: |
          python -m pip install --upgrade pip
          pip install yandex-pgmigrate
      - name: Check out into repository
        uses: actions/checkout@v2
      - name: Run migrations
        run: |
          make run-migrations
      - name: Test
        env:
          DSN: "host=localhost port=5432 user=testserver password=passw0rd dbname=testserverdb sslmode=disable"
        run: make test
